# Lamp Monitor Configuration

# カメラ設定
camera:
  size: [1280, 720] # 解像度 [width, height]
  fps: 20 # フレームレート
  device_id: 0 # カメラデバイスID

# 通知設定
notify:
  worker_url: "https://pi-detection.tai-nakamura.workers.dev" # Cloudflare Workers URL
  secret: "pA!M.k_)!$G.vABQ9aeQmPNM" # 共通鍵（cloudflare-worker-simple.jsのALLOWED_SECRETと一致）
  min_interval_sec: 5 # 同一ランプの再通知最短間隔（秒）- テスト用に短縮

# 判定ロジック設定
logic:
  # HSV色域閾値
  red_hue_range: [[0, 10], [170, 180]] # 赤色相範囲
  red_sat_min: 100 # 赤彩度最小値
  red_val_min: 50 # 赤明度最小値

  green_hue_range: [40, 80] # 緑色相範囲
  green_sat_min: 100 # 緑彩度最小値
  green_val_min: 50 # 緑明度最小値

  # 判定閾値
  red_ratio_thresh: 0.3 # 赤判定の面積比閾値
  green_ratio_thresh: 0.3 # 緑判定の面積比閾値
  min_brightness_v: 30 # 最小明度（暗部ノイズ除外）

  # 形態学的処理
  morphological_kernel: 3 # カーネルサイズ

  # 多数決フィルタ
  frames_window: 5 # 判定窓フレーム数

# ROI設定（ランプ1-12の矩形座標 [x, y, width, height]）
# 合成ダッシュボード用の初期値
rois:
  lamp_1: [80, 80, 240, 120]
  lamp_2: [380, 80, 240, 120]
  lamp_3: [680, 80, 240, 120]
  lamp_4: [980, 80, 240, 120]
  lamp_5: [80, 290, 240, 120]
  lamp_6: [380, 290, 240, 120]
  lamp_7: [680, 290, 240, 120]
  lamp_8: [980, 290, 240, 120]
  lamp_9: [80, 500, 240, 120]
  lamp_10: [380, 500, 240, 120]
  lamp_11: [680, 500, 240, 120]
  lamp_12: [980, 500, 240, 120]

# 合成ダッシュボード設定
synthetic:
  window_size: [500, 300] # ダッシュボードウィンドウサイズ
  lamp_size: [80, 40] # ランプサイズ
  background_color: [50, 50, 50] # 背景色 (BGR)
  text_color: [255, 255, 255] # テキスト色 (BGR)
